-- Kör hela filen i Supabase > SQL Editor > New query.
-- Tabellnamn använder små bokstäver eftersom appen frågar efter players och matches.
create table if not exists public.players (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text unique,
  active boolean not null default true
);
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  player1_id bigint not null references public.players(id) on delete restrict,
  player2_id bigint not null references public.players(id) on delete restrict,
  player1_score integer not null check (player1_score >= 0),
  player2_score integer not null check (player2_score >= 0),
  winner_id bigint not null references public.players(id) on delete restrict,
  played_at date not null default current_date,
  constraint different_players check (player1_id <> player2_id),
  constraint no_draw check (player1_score <> player2_score),
  constraint valid_winner check (winner_id = player1_id or winner_id = player2_id)
);
alter table public.players enable row level security;
alter table public.matches enable row level security;
drop policy if exists "Public can read players" on public.players;
create policy "Public can read players" on public.players for select to anon using (true);
drop policy if exists "Public can read matches" on public.matches;
create policy "Public can read matches" on public.matches for select to anon using (true);
-- MVP: tillåt registrering av matcher från webbappen. Byt till inloggningskrav innan bred lansering.
drop policy if exists "Public can create matches" on public.matches;
create policy "Public can create matches" on public.matches for insert to anon with check (true);
